<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a href="#" class="navbar-brand">
            <i class="fas fa-utensils fa-2x"></i> Where Go Eat
        </a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="search.php" class="nav-item nav-link">Search</a>
                <a href="submit.php" class="nav-item nav-link">Submit</a>
            </div>
            <div class="navbar-nav ms-auto">
                <a href="./signin.php" class="nav-item nav-link">Sign In</a>
            </div>
        </div>
    </div>
</nav>